INSERT INTO STOCKS (ID, SYMBOL, SYMBOL_TYPE, LAST_DIVIDEND, FIXED_DIVIDEND, PAR_VALUE)
	VALUES (1, 'TEA', 'COMMON', 0.00, null, 1);
INSERT INTO STOCKS (ID, SYMBOL, SYMBOL_TYPE, LAST_DIVIDEND, FIXED_DIVIDEND, PAR_VALUE)
	VALUES (2, 'POP', 'COMMON', 0.08, null, 1);
INSERT INTO STOCKS (ID, SYMBOL, SYMBOL_TYPE, LAST_DIVIDEND, FIXED_DIVIDEND, PAR_VALUE)
	VALUES (3, 'ALE', 'COMMON', 0.23, null, 0.60);
INSERT INTO STOCKS (ID, SYMBOL, SYMBOL_TYPE, LAST_DIVIDEND, FIXED_DIVIDEND, PAR_VALUE)
	VALUES (4, 'GIN', 'PREFERRED', 0.08, 0.02, 1);
INSERT INTO STOCKS (ID, SYMBOL, SYMBOL_TYPE, LAST_DIVIDEND, FIXED_DIVIDEND, PAR_VALUE)
	VALUES (5, 'JOE', 'COMMON', 0.13, null, 2.5);

INSERT INTO TRADES (ID, STOCK_ID, OP_TIMESTAMP, NUM_OF_SHARES, OP_TYPE, PRICE)
	VALUES (1, 1, TIMESTAMPADD(MINUTE, -10, NOW()), 200, 'BUY', 2.43);
INSERT INTO TRADES (ID, STOCK_ID, OP_TIMESTAMP, NUM_OF_SHARES, OP_TYPE, PRICE)
	VALUES (2, 1, TIMESTAMPADD(MINUTE, -11, NOW()), 150, 'BUY', 2.40);
INSERT INTO TRADES (ID, STOCK_ID, OP_TIMESTAMP, NUM_OF_SHARES, OP_TYPE, PRICE)
	VALUES (3, 1, TIMESTAMPADD(MINUTE, -12, NOW()), 100, 'SELL', 2.34);
INSERT INTO TRADES (ID, STOCK_ID, OP_TIMESTAMP, NUM_OF_SHARES, OP_TYPE, PRICE)
	VALUES (4, 1, TIMESTAMPADD(MINUTE, -13, NOW()), 487, 'BUY', 2.39);
INSERT INTO TRADES (ID, STOCK_ID, OP_TIMESTAMP, NUM_OF_SHARES, OP_TYPE, PRICE)
	VALUES (5, 1, TIMESTAMPADD(MINUTE, -14, NOW()), 45, 'BUY', 2.37);
INSERT INTO TRADES (ID, STOCK_ID, OP_TIMESTAMP, NUM_OF_SHARES, OP_TYPE, PRICE)
	VALUES (6, 1, TIMESTAMPADD(MINUTE, -15, NOW()), 600, 'SELL', 2.32);
INSERT INTO TRADES (ID, STOCK_ID, OP_TIMESTAMP, NUM_OF_SHARES, OP_TYPE, PRICE)
	VALUES (7, 1, TIMESTAMPADD(MINUTE, -16, NOW()), 245, 'BUY', 2.35);
INSERT INTO TRADES (ID, STOCK_ID, OP_TIMESTAMP, NUM_OF_SHARES, OP_TYPE, PRICE)
	VALUES (8, 1, TIMESTAMPADD(MINUTE, -17, NOW()), 37, 'BUY', 2.33);

INSERT INTO TRADES (ID, STOCK_ID, OP_TIMESTAMP, NUM_OF_SHARES, OP_TYPE, PRICE)
	VALUES (9, 4, TIMESTAMPADD(MINUTE, -10, NOW()), 200, 'BUY', 2.43);
INSERT INTO TRADES (ID, STOCK_ID, OP_TIMESTAMP, NUM_OF_SHARES, OP_TYPE, PRICE)
	VALUES (10, 4, TIMESTAMPADD(MINUTE, -11, NOW()), 150, 'BUY', 2.40);
INSERT INTO TRADES (ID, STOCK_ID, OP_TIMESTAMP, NUM_OF_SHARES, OP_TYPE, PRICE)
	VALUES (11, 4, TIMESTAMPADD(MINUTE, -12, NOW()), 100, 'SELL', 2.34);
INSERT INTO TRADES (ID, STOCK_ID, OP_TIMESTAMP, NUM_OF_SHARES, OP_TYPE, PRICE)
	VALUES (12, 4, TIMESTAMPADD(MINUTE, -13, NOW()), 487, 'BUY', 2.39);
INSERT INTO TRADES (ID, STOCK_ID, OP_TIMESTAMP, NUM_OF_SHARES, OP_TYPE, PRICE)
	VALUES (13, 4, TIMESTAMPADD(MINUTE, -14, NOW()), 45, 'BUY', 2.37);
INSERT INTO TRADES (ID, STOCK_ID, OP_TIMESTAMP, NUM_OF_SHARES, OP_TYPE, PRICE)
	VALUES (14, 4, TIMESTAMPADD(MINUTE, -15, NOW()), 600, 'SELL', 2.32);
INSERT INTO TRADES (ID, STOCK_ID, OP_TIMESTAMP, NUM_OF_SHARES, OP_TYPE, PRICE)
	VALUES (15, 4, TIMESTAMPADD(MINUTE, -16, NOW()), 245, 'BUY', 2.35);
INSERT INTO TRADES (ID, STOCK_ID, OP_TIMESTAMP, NUM_OF_SHARES, OP_TYPE, PRICE)
	VALUES (16, 4, TIMESTAMPADD(MINUTE, -17, NOW()), 37, 'BUY', 2.33);
	
INSERT INTO TRADES (ID, STOCK_ID, OP_TIMESTAMP, NUM_OF_SHARES, OP_TYPE, PRICE)
	VALUES (17, 2, TIMESTAMPADD(MINUTE, -5, NOW()), 37, 'BUY', 2.45);
	
INSERT INTO TRADES (ID, STOCK_ID, OP_TIMESTAMP, NUM_OF_SHARES, OP_TYPE, PRICE)
	VALUES (18, 3, TIMESTAMPADD(MINUTE, -5, NOW()), 37, 'BUY', 6.45);