CREATE TABLE "STOCKS"
	("ID" NUMBER(10,0) PRIMARY KEY,
	 "SYMBOL" VARCHAR2(5 CHAR) NOT NULL,
	 "SYMBOL_TYPE" VARCHAR2(9 CHAR) NOT NULL,
	 "LAST_DIVIDEND" NUMBER(12,2),
	 "FIXED_DIVIDEND" NUMBER(10,5),
	 "PAR_VALUE" NUMBER(12,2)
	);
CREATE TABLE "TRADES"
	("ID" NUMBER(10,2) PRIMARY KEY,
	 "STOCK_ID" NUMBER(10,0),
	 "OP_TIMESTAMP" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	 "NUM_OF_SHARES" NUMBER(15,5) NOT NULL,
	 "OP_TYPE" VARCHAR2(9 CHAR) NOT NULL,
	 "PRICE" NUMBER(15,5) NOT NULL
	);

CREATE SEQUENCE STOCK_ID_SEQ START WITH 100 INCREMENT BY 10;
CREATE SEQUENCE TRADE_ID_SEQ START WITH 100 INCREMENT BY 10;

CREATE INDEX TRADE_INDEX ON "TRADES" ("OP_TIMESTAMP");

ALTER TABLE TRADES ADD CONSTRAINT "TRADES_STOCKS_FK"
FOREIGN KEY ("STOCK_ID") REFERENCES "STOCKS" ("ID");